### ISSUE TITLE
Jobs images must be in sync with component they updating

### ISSUE THREAD

**Issue by l0kix2** [ytsaurus/ytsaurus-k8s-operator#157]
Not sure if it is a problem for all the components, but it is bug for master exit read only job, because if you run master on 23.1 ytsaurus image and master read only job on 23.2 ytsaurus image job hangs because there is no such command in 23.1.

Maybe all nil instance spec images must be set to core in default webhook and we can use instanceSpec.Image in job and server.

**Comment by achulkov2** [comment]
This is also true for the scheduler init job. When updating schedulers only the operation archive is not migrated to the version from the scheduler image.
