### ISSUE TITLE
CHYT resource should separate setting new version as default from creating the default ch_public clique

### ISSUE THREAD

**Issue by achulkov2** [ytsaurus/ytsaurus-k8s-operator#312]
Right now the `makeDefault: true` setting in the CHYT resource leads to the new binary being [set](https://github.com/ytsaurus/yt-k8s-operator/blob/main/pkg/components/chyt.go#L97) as the default CH version, as well as the [creation](https://github.com/ytsaurus/yt-k8s-operator/blob/main/pkg/components/chyt.go#L182) of the default `ch_public` clique. 
These should be two separate options, as the latter might mess up the `ch_public` clique configuration if it already exists.

**Comment by l0kix2** [comment]
I guess this is fixed here https://github.com/ytsaurus/ytsaurus-k8s-operator/pull/347
@achulkov2 reopen please if i'm wrong
